version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5
    working_directory: ~/rails-felmy-app05/src
    steps:
      - checkout:
          path: ~/rails-felmy-app05
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.5-node
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app05_test
          MYSQL_USER: root
      - image: selenium/standalone-chrome-debug:latest
        name: chrome
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/rails-felmy-app05/src
    steps:
      - checkout:
          path: ~/rails-felmy-app05
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate:reset
      - run:
          name: webpacker compile
          command: bundle exec rake assets:precompile
      - run:
          name: Seed data-1
          command: bundle exec rails db:seed SECTION=2
      - run:
          name: Seed data-2
          command: bundle exec rails db:seed SECTION=7
      - run:
          name: test
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate:reset RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1 -a $HEROKU_APP_NAME
      - run:
          name: Seed data-1
          command: heroku run bundle exec rails db:seed SECTION=2 RAILS_ENV=production -a $HEROKU_APP_NAME
      - run:
          name: Seed data-2
          command: heroku run bundle exec rails db:seed SECTION=7 RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
